version: '3'
services:
  postgres:
    image: postgres:10.3
    ports:
     - "5432:5432"
    volumes:
      - ./data/schema.ddl:/docker-entrypoint-initdb.d/1-create-schema.sql
      - ./data/books.sql:/docker-entrypoint-initdb.d/2-load-books.sql
      - ./data/log_entries.sql:/docker-entrypoint-initdb.d/3-log_entries.sql
    environment:
      - POSTGRES_USER=booklog
      - POSTGRES_PASSWORD=booklog

